### ISSUE TITLE
Rama actual

### ISSUE THREAD

**Issue by martefranco** [Emilianosanchezlopez/ADMAINBIT#2]
@Emilianosanchezlopez Voy a trabajar sobre la Emi-branch-ad

Y dejo intacta la master hasta que mejoremos algo., si veo el fin de semana como trabajarlo directo desde Visual Studio Code te aviso

**Comment by Emilianosanchezlopez** [comment]
Ok Entonces creo otra branch para trabajarla yo y comparamos los cambios entre las dos branchs. :taco: :taco:
